module.exports = {
    DEFAULT_ERROR: 'Une erreur est apparue, réessayez plus tard',
    INVALID_BODY_DATA: 'Certains paramètres n\'existent pas ou sont invalides',
    TOKEN_NOT_PRESENT: 'Le token d\'authentification n\'est pas présent dans l\'entête de la requête',
    INVALID_TOKEN: 'Le token d\'authentification n\'est pas valide',

    // USER
    USER_BODY_INVALID_NAME_LENGTH: 'Le nom doit posséder entre 3 et 120 caractères',
    USER_BODY_INVALID_NAME_FORMAT: 'Le nom ne doit pas posséder d\'espace et de caractères spéciaux',
    USER_BODY_INVALID_PASSWORD_LENGTH: 'Le mot de passe doit posséder entre 4 et 120 caractères',
    USER_NOT_EXISTING: 'Aucun utilisateur ne correspond à ces identifiants',
    USER_NAME_ALREADY_USE: 'Ce nom est déjà utilisé par un autre utilisateur',
    USER_CREATION_FAILED: 'Une erreur inconnue s\'est produite lors de l\'inscription. Merci de réessayer plus tard.',
    USER_LOGGED_WITH_SUCCESS: 'Vous vous êtes connecté avec succès',
    USER_CREATED_WITH_SUCCESS: 'Vous vous êtes inscrit avec succès',
}
